Testing random Python code

In [53]:
import kcgof
import kcgof.log as klog
import kcgof.util as util
import torch
import torch.distributions as dists

## Torch seed context

In [77]:
with util.TorchSeedContext(seed=3):
    W = torch.randn(3, 5)
    stn = dists.Normal(0,1)
    sam = stn.sample((3,1))

In [78]:
W

tensor([[ 0.8033,  0.1748,  0.0890, -0.6137,  0.0462],
        [-1.3683,  0.3375,  1.0111, -1.4352,  0.9774],
        [ 0.5220,  1.2379, -0.8646,  0.2990,  0.4192]])

In [79]:
sam

tensor([[-0.0799],
        [ 0.9264],
        [ 0.8157]])

In [80]:
torch.randn(3,5)

tensor([[ 0.3352, -1.1114, -2.4282,  0.0088,  0.0051],
        [-1.6722,  0.8699, -2.2548, -0.4953, -0.5367],
        [-0.2155, -1.1237, -0.5077,  0.0700,  0.0858]])