A notebook to quickly check code in `kcgof.util`.


In [37]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%config InlineBackend.figure_format = 'svg'
#%config InlineBackend.figure_format = 'pdf'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [58]:
import numpy as np
import torch
import torch.distributions as dists

import kcgof
import kcgof.log as klog
import kcgof.util as util
import kcgof.cdensity as cden
import kcgof.cdata as cdat
import kcgof.cgoftest as cgof
import kcgof.kernel as ker
import kcgof.plot as plot

In [59]:
import matplotlib
import matplotlib.pyplot as plt

# font options
font = {
    #'family' : 'normal',
    #'weight' : 'bold',
    'size'   : 20
}

plt.rc('font', **font)
plt.rc('lines', linewidth=2)
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42


## Median heuristic

In [68]:
X = torch.rand(8, 3)

In [69]:
# Y = torch.rand(7, 3)
D = torch.sqrt(util.pt_dist2_matrix(X, X))
D

tensor([[0.0000e+00, 3.3753e-01, 6.6945e-01, 4.7189e-01, 1.7060e-01, 5.1734e-01,
         5.9612e-01, 4.4713e-01],
        [3.3753e-01, 0.0000e+00, 7.4225e-01, 8.0306e-01, 4.2888e-01, 8.4124e-01,
         4.9341e-01, 2.1576e-01],
        [6.6945e-01, 7.4225e-01, 4.8828e-04, 8.1510e-01, 7.8003e-01, 8.4191e-01,
         7.0767e-01, 8.1376e-01],
        [4.7189e-01, 8.0306e-01, 8.1510e-01, 0.0000e+00, 4.7899e-01, 3.0326e-01,
         8.7884e-01, 8.5805e-01],
        [1.7060e-01, 4.2888e-01, 7.8003e-01, 4.7899e-01, 0.0000e+00, 4.4125e-01,
         7.6123e-01, 5.7059e-01],
        [5.1734e-01, 8.4124e-01, 8.4191e-01, 3.0326e-01, 4.4125e-01, 0.0000e+00,
         1.0498e+00, 9.6283e-01],
        [5.9612e-01, 4.9341e-01, 7.0767e-01, 8.7884e-01, 7.6123e-01, 1.0498e+00,
         0.0000e+00, 3.4090e-01],
        [4.4713e-01, 2.1576e-01, 8.1376e-01, 8.5805e-01, 5.7059e-01, 9.6283e-01,
         3.4090e-01, 0.0000e+00]])

In [76]:
n = X.shape[0]
I = torch.tril_indices(n, n, -1)
I

tensor([[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7,
         7, 7, 7, 7],
        [0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2,
         3, 4, 5, 6]])

In [77]:
D[I[0], I[1]]

tensor([0.3375, 0.6694, 0.7423, 0.4719, 0.8031, 0.8151, 0.1706, 0.4289, 0.7800,
        0.4790, 0.5173, 0.8412, 0.8419, 0.3033, 0.4412, 0.5961, 0.4934, 0.7077,
        0.8788, 0.7612, 1.0498, 0.4471, 0.2158, 0.8138, 0.8580, 0.5706, 0.9628,
        0.3409])

In [78]:
torch.median(D[I[0], I[1]])

tensor(0.5961)

In [79]:
util.pt_meddistance(X)

0.5961202383041382

In [74]:
# subsample rows
n = X.shape[0]
ind = np.random.choice(n, 3, replace=False)

In [67]:
ind

array([18, 45, 13])

In [48]:
X[ind]

tensor([[0.3726, 0.2139, 0.2157],
        [0.3248, 0.2251, 0.5792],
        [0.4924, 0.8455, 0.2665]])